In [6]:
import pandas as pd

df = pd.read_csv(r"D:\project\pandas-ecommerce-analysis\data\raw\Pakistan Largest Ecommerce Dataset.csv",
encoding='latin1'
)
df.head()

C:\Users\37450\AppData\Local\Temp\ipykernel_28392\3062179304.py:3: DtypeWarning: Columns (0: increment_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\project\pandas-ecommerce-analysis\data\raw\Pakistan Largest Ecommerce Dataset.csv",

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016,7,Jul-16,7-2016,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016,7,Jul-16,7-2016,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016,7,Jul-16,7-2016,FY17,3.0
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016,7,Jul-16,7-2016,FY17,4.0
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016,7,Jul-16,7-2016,FY17,5.0

In [7]:
df["new_col"] = 1
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID,new_col
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,\N,...,7/1/2016,#REF!,"1,950",2016,7,Jul-16,7-2016,FY17,1.0,1
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,\N,...,7/1/2016,Gross,240,2016,7,Jul-16,7-2016,FY17,2.0,1
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,\N,...,7/1/2016,Gross,"2,450",2016,7,Jul-16,7-2016,FY17,3.0,1
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7/1/2016,Net,360,2016,7,Jul-16,7-2016,FY17,4.0,1
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,\N,...,7/1/2016,Valid,"1,110",2016,7,Jul-16,7-2016,FY17,5.0,1

In [8]:
import sys
print(sys.executable)

d:\project\pandas-ecommerce-analysis\.venv\Scripts\python.exe